### ISSUE TITLE
Multibyte characters not working with microgateway

### ISSUE THREAD

**Issue by iainsoed** [strongloop/microgateway#61]
When testing the microgateway with api designer, if calling an endpoint that returns json containing multibyte characters, the response is truncated, and the test tool displays:

SyntaxError: Unexpected end of JSON input

Looking in the browser trace we can see that the expected response which is:

{"array":[{"name": "Ã¡"}]}

is returned as:

{"array":[{"name":"Ã¡"}

missing the two closing square and curly brackets.

APAR: https://jazz609.hursley.ibm.com:9443/jazz/web/projects/APIM#action=com.ibm.team.workitem.viewWorkItem&id=56533

Fixed in microgateway version| Target Release Stream | Date Shrinkwrapped
------------------|------------ | ------------- 
1.6.3|5060|TBD
1.6.3|5070|TBD
1.6.3|master|TBD

**Comment by jgeddes2001** [comment]
https://jazzl03.hursley.ibm.com:9443/ccm/web/projects/API%20Management#action=com.ibm.team.workitem.viewWorkItem&id=15765

**Comment by jgeddes2001** [comment]
https://github.com/strongloop/microgateway/pull/63 << out for review.. appears this fixes the issue..

**Comment by jgeddes2001** [comment]
1. Install apiconnect
`npm install  -g apiconnect`
2. Go to the global directory where apiconnect was installed (may vary based on OS)
`cd /usr/local/lib/node_modules/apiconnect/`
3. Update to grab latest microgateway version
`vi package.json` << change `"version": "1.6.2",` to `"version": "1.6.3",` for the microgateway
4. Pull in the latest microgateway under apiconnect
`npm install microgateway`
5. Verify fix is there
`cat /usr/local/lib/node_modules/apiconnect/node_modules/microgateway/lib/postflow/index.js | grep Content`
Should have two lines:
- res.set('Content-Length', Buffer.byteLength(body, 'utf8'));
- res.set('Content-Length', 0); (edited)

**Comment by iainsoed** [comment]
Just added a table for tracking where the fix has gone.  @kraman does the above table make sense for this component?  we've used it before for apiconnect-wsdl.

**Comment by tonyffrench** [comment]
@iainsoed @jgeddes2001 i assume we can close this issue?

**Comment by iainsoed** [comment]
yes, not heard anything back from customer on this.

**Comment by iainsoed** [comment]
Please can it be confirmed where this fix was shrinkwrapped, so we know whether to expect this fix in the appliance on 5063 and 5071?

**Comment by jgeddes2001** [comment]
@iainsoed I have confirmed this fix is in the microgateway shipped with APIm 5071.. via
`apic microgateway --server apimdev2001.hursley.ibm.com --name apim-microgateway`
