### ISSUE TITLE
rate limit

### ISSUE THREAD

**Issue by tksheen** [strongloop/microgateway#69]
hitting the following error when I'm trying to do a load test on the microgateway. 

Error: rate-limit: limit exceeded x-ibm-unnamed-rate-limit

where is the rate limit set?

**Comment by ozairs** [comment]
Default rate plan of 100 calls / hour is pre-defined. Do you see the following headers in the response

	```
	X-RateLimit-Limit →name=rate-limit,100
	X-RateLimit-Remaining →name=rate-limit,9
	X-RateLimit-Reset →name=rate-limit,22
        ```

**Comment by king729** [comment]
how can i replace this rule

**Comment by jgeddes2001** [comment]
@king729 Assuming you are running in "standalone" mode.. not integrated with APIm.. If so take a look at LAPTOP_RATELIMIT documented here https://www.ibm.com/support/knowledgecenter/en/SSMNED_5.0.0/com.ibm.apic.install.doc/rapic_environment_vars_mg.html and here https://github.com/strongloop/microgateway-datastore#environment-variables
