### ISSUE TITLE
[help] Oauth2

### ISSUE THREAD

**Issue by JHuiG** [strongloop/microgateway#73]
Hi,

Is there any tutorial on e oauth2.?

**Comment by ozairs** [comment]
We are working on putting together the docs. Is there any particular code flow (az code, password, etc ... that your interested in?

**Comment by gjianhui** [comment]
Hi @ozairs . thks for the update.

I have problem during the configuration. esp on the all the URL required.

Also do we need to start the auth server as shown in the /test example?

For your advice, please.

Thanks.

**Comment by ozairs** [comment]
can you provide your Swagger so I can reproduce the errors in your environment?

**Comment by ahwing210** [comment]
Hi ozairs,

I am following [this tutorial](https://developer.ibm.com/apiconnect/2017/04/11/securing-apis-using-oauth-in-apiconnect/). I am also having trouble configuring OAuth2...
Wondering if configuring OAuth2 actually requires API Connect / IBM Bluemix (i.e. only using the opensource Microgateway is NOT enough)?

I keep getting....
{
    "error": "invalid_client",
    "error_description": "Authentication error"
}

It seems I need to add a "new application" and get the client ID and client secret (as suggested in this [tutorial](https://www.youtube.com/watch?v=L_fLiDz7fv8&feature=youtu.be))

Thanks for your time!

**Comment by ozairs** [comment]
The toolkit uses a default application with client_id = default and client_secret = SECRET. Did you try those values?

Not that the API microgateway is not used by API Connect in Bluemix
