### ISSUE TITLE
How to connect loopback api with microgeteway

### ISSUE THREAD

**Issue by kimoudev** [strongloop/microgateway#74]
I have this error
Error: api-matcher failed to match to any API
I did exactly as indicated..i'm on mac.
help please

**Comment by ozairs** [comment]
Can you provide details on what you did exactly? Logs? curl commands?

**Comment by kimoudev** [comment]
followed installation instructions and test below, including definition of yaml file in definitions/sample
node sample.js appears to start-up correctly, issuing 2 warnings on deprecated context middleware
curl http://localhost:3000/sample/echo -- and receive message {"name": "PreFlowError". "message": "unable to process the request"}
message in cli displays "Error: api-loader failed to load any API"
not sure if it is important, but i did note in the .datastore file that the following record is stored
{"snapshot":"C:\Users\Patrick\Desktop\microgateway\test/definitions/sample","port":36042}  exactly like this..

**Comment by ozairs** [comment]
Looks like the definitions folder was not picked up by the startup script. I just recently updated the `README.md` instructions to move the `definitions` folders into root folder. That might make it easier to find the YAML files.

**Comment by kimoudev** [comment]
yes i move definitions folders into root folder but this Error: ```
Cannot find module 'node_modules/loopback'
Error: Cannot find module 'node_modules/loopback'
Error: Cannot find module 'node_modules/loopback'
```

**Comment by ozairs** [comment]
hmmm .. make sure you have that listed in the `package.json` file. I suggest removing the existing `node_modules` directory and performing a clean `npm install`.

**Comment by kimoudev** [comment]
I get the same error when running in CentOS 7
In Step 3 it says to go to the root folder which is the same folder as Step 2 and when I create the sample.js file there, the require for the microgw fails as it is not in "../lib/microgw" but "./lib/microgw"
after changing that I still have the same "failed to load any API" error......same problem with @geekosphere-net   i tried on MAC same problem @ozairs

**Comment by ozairs** [comment]
Here are the steps I performed to get the microgateway 

```
1. Clone the repository with the command: `git clone https://github.com/strongloop/microgateway.git`.
	2. Switch directory `cd microgateway/`.
        3. Create file called `microgateway.js` with the following
            
```
'use strict';

var mg = require('./lib/microgw');
var fs = require('fs');

// config dir
process.env.CONFIG_DIR = __dirname + '/definitions/myapp';
process.env.NODE_ENV = 'development';
mg.start(4000);

```            
	4. Copy the file `microgateway.js` into `$PWD/microgateway/microgateway.js`. 
	5. The microgateway uses a YAML file to protect access to the API. Copy a sample YAML file into `$PWD/microgateway/config/definitions/myapp/mysample.yaml` and create the appropriate directories.
```
If you need a sample yaml file, you can use one here (just rename the file to remove the .txt extension)
[pokemon_1.0.0.yaml.txt](https://github.com/strongloop/microgateway/files/1085227/pokemon_1.0.0.yaml.txt)

**Comment by kimoudev** [comment]
hi..i make exactly like indicated but i got this error....   `{"name":"PreFlowError","message":"unable to process the request"}`  @ozairs

**Comment by yanaisama** [comment]
Try enabling DEBUG info and collect log on file   /root/.apiconnect/apic.log. It will say whats is happening.
To enable debug, run:        #APIC_LOG_FILE_LEVEL=debug node sample.js     instead of    #node sample.js

**Comment by No9** [comment]
@kimoudev FYI you will get `Error: api-matcher failed to match to any API` 
when you run to the wrong path of the app
e.g. `/` instead of `/sample/echo`

**Comment by kimoudev** [comment]
@No9  Please I can have more details about the path ..
Because I did exactly as indicated  `$PWD/microgateway/config/definitions/myapp/mysample.yaml` but a same error...

**Comment by No9** [comment]
Hey @kimoudev the http path i.e. `http://localhost:4000/sample/echo` if you are using the microgateway.js example given above

**Comment by kimoudev** [comment]
hey @No9  i get this perfectly `{"text":"Hello World"}` but how to get IBM microgateway manager interface please...

**Comment by No9** [comment]
@kimoudev do you mean the UI for defining and editing API definitions?
i.e. this UI? http://heidloff.net/wp-content/uploads/2016/04/apiconnect5.png 
If so you can do the following: 
if you haven't installed API Connect already
```
$ npm install apiconnect -g
```
Then simply 
```
$ cd microgateway/definitions/myapp
$ apic edit
```

**Comment by kimoudev** [comment]
@No9  thank you very much

**Comment by No9** [comment]
@kimoudev no problem thanks for taking it for a drive - this feedback is really useful.
BTW if you're happy that this is resolved please could you close the issue
