### ISSUE TITLE
APIs unavailable during publishing of API Manager

### ISSUE THREAD

**Issue by yanaisama** [strongloop/microgateway#76]
Is there a way of don't get down the existing APIs while updating the microgateway configuration by API Connect Manager?

Luiz Yanai

**Comment by jgeddes2001** [comment]
@yanaisama Publishing new APIs to the microgateway when data is from APIConnect shouldn't cause an outage for existing APIs... Are there any errors in the logs?

**Comment by yanaisama** [comment]
I tested again and I did't have any outage. No errors were found.  The parameter APIMANAGER_REFRESH_INTERVAL impacts the time elapse between publication and new API availability?

**Comment by jgeddes2001** [comment]
@yanaisama That should only impact the new API availability if the webhook notifying of the change did not reach the gateway (ie network connectivity blip), we will receive the update via the next APIMANAGER_REFRESH_INTERVAL
