### ISSUE TITLE
Microgateway graphic interface

### ISSUE THREAD

**Issue by kimoudev** [strongloop/microgateway#78]
I not understand clearly.
After installation, we can manupile Api graphically as indicated.
`https://strongloop.com/strongblog/introducing-api-microgateway-programmable-open-source-gateway-apis/.`
Because I did the installation and I get 
`{"text":"Hello World"}`

Or there is a difference between IBM api connect and Microgateway?.

Thank you

**Comment by yanaisama** [comment]
Microgateway is only an runtime to execute some policies defined in YAML files (Swagger). The only interface that it has is from datastore. Tha API Connect is an IBM product that you can use to edit YAML files easily. Actually you can download a similar interface (API Connect Developer Tool).  Using  npm install -g apiconnect.

**Comment by No9** [comment]
Hey @kimoudev 
Is this the same problem as you asked here? https://github.com/strongloop/microgateway/issues/74#issuecomment-310167644 
If so would you mind closing this too?
