### ISSUE TITLE
Typo in setup of "Hello World"

### ISSUE THREAD

**Issue by dpbabcock** [strongloop/microgateway#80]
In following the instructions, I got an exception because the line

var mg = require('../lib/microgw');

in sample.js

is being executed from the $HOME/microgateway directory per the instructions and the ".." is effectively looking for that library as 

$HOME/lib/microgw 

instead of its actual location at 

$HOME/microgateway/lib.microgw

I edited the sample.js file to change this line to:

var mg = require('./lib/microgw');

(i.e. changed ".." to "." in the require call)

and the "hello world" worked. You need to fix this typo or folks not familiar with what's going on will get frustrated.

**Comment by ozairs** [comment]
thank you. Good catch :)

**Comment by ahwing210** [comment]
It seems the line `var fs = require('fs');` can also be removed?
Since fs is not used subsequently.

**Comment by ozairs** [comment]
Thanks for the feedback. I'll review with our Engineering team.
