### ISSUE TITLE
add loopback-component-cas?

### ISSUE THREAD

**Issue by sbechet** [strongloop/microgateway#92]
Hello,

Actualy, we use CAS specification for legacy app.

Do you think that the integration of [this component](http://github.com/sbechet/loopback-component-cas) with microgateway could have an interest for you and be done quickly?

**Comment by tonyffrench** [comment]
At this moment in time we are more interested in improving the `microgateway` as an extensible framework (performance, core capabilities, etc), making it easy to add such functionality as external policy. Thanks.
